spring:
  application:
    name: aop-example
  datasource:
    url: jdbc:postgresql://localhost:5432/aop_impl
    username: postgres
    password: YassMel97
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE